---
- name: Install webapp
  hosts: build
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - maven
          - openjdk-11-jdk
          - git
          - tomcat9
        state: present

    - name: Clone repository
      git:
        repo: https://github.com/yankils/hello-world.git
        dest: /home/dmitry/hello-world
        update: yes

    - name: Build webapp
      command: mvn package
      args:
        chdir: /home/webapp

